src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article extends Page
{
    public const TYPE = 'article';
    
    /**
     * @ORM\ManyToMany(targetEntity=Product::class)
     */
    private Collection $products;
    
    /**
     * @ORM\Column(type="integer", options={"default": 0})
     */
    private int $views = 0;
    
    public function __construct()
    {
        parent::__construct();
        $this->products = new ArrayCollection();
    }
    
    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }
    
    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
        }
    
        return $this;
    }
    
    public function removeProduct(Product $product): self
    {
        $this->products->removeElement($product);
        
        return $this;
    }
    
    /**
     * @return int
     */
    public function getViews(): int
    {
        return $this->views;
    }
    
    /**
     * @param int $views
     *
     * @return $this
     */
    public function setViews(int $views): self
    {
        $this->views = $views;
    
        return $this;
    }
    
    public function getUri(): ?string
    {
        return parent::getUri() ?? 'articles/...';
    }
    
    public function incrementViews(): void
    {
        $this->views++;
    }
}

src/Entity/Geo.php
<?php

namespace App\Entity;

use App\Entity\Contracts\HasCatalogSettingsInterface;
use App\Entity\Traits\CatalogSettingsTrait;
use App\Model\GeoProduct\AbstractGeoProduct;
use App\Model\GeoProduct\RulonnyieShtoryiGeoProduct;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\EntityListeners({"App\EntityListener\GeoListener"})
 */
abstract class Geo extends Page implements HasCatalogSettingsInterface
{
    
    use CatalogSettingsTrait;
    
    public const TYPE = 'geo';
    /**
     * @var AbstractGeoProduct
     */
    protected $geoProduct;
    
    /**
     * @return AbstractGeoProduct
     */
    public function getGeoProduct(): AbstractGeoProduct
    {
        if (null === $this->geoProduct) {
            $this->geoProduct = AbstractGeoProduct::create($this->getGeoProductType());
        }
        
        return $this->geoProduct;
    }
    
    public function getCardHeader(): string
    {
        return $this->getH1() . ' цена';
    }
    
    public function getCardDescription(): string
    {
        return sprintf('<p><span><b>Материал:</b> ткань, алюминий, пластик, дерево.</span> <span><b>Цвет:</b> на выбор.</span> <span><b>Размеры:</b> стандартные и под заказ</span> <span><b>Тип:</b> горизонтальные и вертикальные.</span> <span><b>Виды:</b> алюминиевые, пластиковые, деревянные, тканевые.</span> <span><b>Помещения:</b>&nbsp;терраса&nbsp;</span><span><b>Управление:</b> механическое и автоматическое</span> <span><b>Срок изготовления и установки:</b> 2-7 дней (зависит от сложности и объема).</span> <span><b>Замер:</b> бесплатный (при оформлении и оплате заказа).</span> <span><b>Доставка и установка %s:</b> в $city_and_region_prepositional.</span> <span>Возможна доставка и установка по России</span></p>',
            $this->getGeoProduct()->getNameGenitive());
    }
    
    public function getCardImageUrl(): string
    {
        return $this->getGeoProduct()->getCardImage();
    }
    
    public function getTypeFilter(): string
    {
        return $this->getGeoProductType() === RulonnyieShtoryiGeoProduct::TYPE ? '133' : '86,132,178';
    }
    
    public function isShowCatalog(): bool
    {
        return $this instanceof City
               || in_array($this->getUri(), ['moskovskoy-oblasti', 'rulonnyie-shtoryi/moskovskoy-oblasti']);
    }
    
    public function getBaseCatalogUri(): string
    {
        return $this->getGeoProductType() === RulonnyieShtoryiGeoProduct::TYPE ? 'rulonnyie-shtoryi' : 'vertikalnye-zhalyuzi-na-okna';
    }
}

src/Entity/Page.php
<?php

namespace App\Entity;

use App\Entity\Contracts\HasExamplesInterface;
use App\Entity\Contracts\TurboPageInterface;
use App\Entity\Traits\RatingTrait;
use App\Model\GeoProduct\RulonnyieShtoryiGeoProduct;
use App\Model\GeoProduct\ZhalyuziGeoProduct;
use DateTime;
use DateTimeImmutable;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PageRepository")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="page_type", type="string")
 * @ORM\DiscriminatorMap({
 *     District::TYPE = "District",
 *     Metro::TYPE = "Metro",
 *     City::TYPE = "City",
 *     Product::TYPE = "Product",
 *     Catalog::TYPE = "Catalog",
 *     Simple::TYPE = "Simple",
 *     Location::TYPE = "Location",
 *     Roman::TYPE = "Roman",
 *     Roll::TYPE = "Roll",
 *     Markiz::TYPE = "Markiz",
 *     Geo::TYPE = "Geo",
 *     Calculator::TYPE = "Calculator",
 *     Article::TYPE = "Article",
 * })
 * @ORM\Table(indexes={
 *     @ORM\Index(name="IDX_NAME_FULLTEXT", columns={"name"}, flags={"fulltext"})
 * })
 * @Vich\Uploadable
 * @ORM\HasLifecycleCallbacks()
 */
abstract class Page implements TurboPageInterface, HasExamplesInterface
{
    use RatingTrait;
    
    const MIN_RATING_VALUE = 4.7;
    const MAX_RATING_VALUE = 4.9;
    const MIN_RATING_COUNT = 8;
    const MAX_RATING_COUNT = 35;
    const DEFAULT_WORK_EXAMPLES_LIMIT = 3;
    
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;
    
    /**
     * @ORM\Column(type="string", length=255)
     */
    protected ?string $name = '';
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected ?string $h1 = null;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected ?string $nameGenitive = null;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected ?string $nameNominative = null;
    
    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $uri;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $title = null;
    
    /**
     * @ORM\Column(type="text", length=255, nullable=true)
     */
    protected $description = null;
    
    /**
     * @ORM\Column(type="boolean")
     */
    protected $published = 1;
    
    /**
     * @ORM\Column(type="boolean", options={"default": 0})
     */
    protected $yml = false;
    
    /**
     * @ORM\Column(type="boolean", options={"default": 0})
     */
    protected $turbo = false;
    
    /**
     * @ORM\Column(type="boolean", options={"default": 1})
     */
    protected $showSeoText = true;
    
    /**
     * @ORM\Column(type="datetime")
     */
    protected $created_at;
    
    /**
     * @ORM\Column(type="datetime")
     */
    protected $modified_at;
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Page", inversedBy="pages")
     */
    protected ?Page $parent;
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Page", mappedBy="parent")
     * @ORM\OrderBy({"ordering" = "ASC", "id" = "ASC",})
     */
    protected $pages;
    
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $content;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $seoImage;
    
    /**
     * @Vich\UploadableField(mapping="seo_images", fileNameProperty="seoImage")
     * @var File
     */
    protected $seoImageFile;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $ourWorksFolder;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $cardImage;
    
    /**
     * @Vich\UploadableField(mapping="card_images", fileNameProperty="cardImage")
     * @var File
     */
    protected $cardImageFile;
    
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $cardDescription;
    
    /**
     * @var string
     * @ORM\Column(type="string",options={"default": App\Model\GeoProduct\ZhalyuziGeoProduct::TYPE})
     */
    protected $geoProductType = ZhalyuziGeoProduct::TYPE;
    /**
     * @ORM\Column(type="json", nullable=true)
     */
    protected ?array $popularCategories = [];
    
    /**
     * @ORM\ManyToMany(targetEntity=WorkExample::class, mappedBy="pages")
     * @ORM\OrderBy({"position" = "ASC"})
     */
    private Collection $workExamplesOfPage;
    
    /**
     * @ORM\Column(type="json", nullable=true)
     */
    protected ?array $settings = [];
    
    /**
     * @ORM\Column(type="integer",nullable=false, options={"default": 0})
     */
    protected int $ordering = 0;
    
    /**
     * @ORM\Column(nullable=false, options={"default": 0.7})
     */
    protected float $priority = 0.7;
    
    /**
     * @ORM\Column(type="json", nullable=true)
     */
    protected ?array $faq = [];
    
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected ?string $faqTitle = null;
    
    public function __construct()
    {
        $this->created_at  = new DateTimeImmutable();
        $this->modified_at = new DateTimeImmutable();
        $this->pages       = new ArrayCollection();
        $this->generateRatingAndCount();
        $this->workExamplesOfPage = new ArrayCollection();
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }
    
    public function getName(): ?string
    {
        return $this->name;
    }
    
    public function setName(string $name)
    {
        $this->name = $name;
        
        return $this;
    }
    
    public function getUri(): ?string
    {
        return $this->uri;
    }
    
    public function getPath(): string
    {
        if ($this->uri === '/') {
            return '/';
        }
        
        return '/' . $this->uri . '/';
    }
    
    public function setUri(string $uri)
    {
        $this->uri = trim($uri);
        
        return $this;
    }
    
    public function setPath(string $path)
    {
        return $this->setUri($path);
    }
    
    public function getTitle(): ?string
    {
        return $this->title;
    }
    
    public function setTitle(?string $title)
    {
        $this->title = $title;
        
        return $this;
    }
    
    public function getDescription(): ?string
    {
        return $this->description;
    }
    
    public function setDescription(?string $description)
    {
        $this->description = $description;
        
        return $this;
    }
    
    public function getPublished(): ?bool
    {
        return $this->published;
    }
    
    public function setPublished(bool $published)
    {
        $this->published = $published;
        
        return $this;
    }
    
    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->created_at;
    }
    
    public function setCreatedAt(DateTimeInterface $created_at): Page
    {
        $this->created_at = $created_at;
        
        return $this;
    }
    
    public function getModifiedAt(): ?DateTimeInterface
    {
        return $this->modified_at;
    }
    
    public function setModifiedAt(DateTimeInterface $modified_at)
    {
        $this->modified_at = $modified_at;
        
        return $this;
    }
    
    public function getParent()
    {
        return $this->parent;
    }
    
    public function setParent(?self $parent)
    {
        $this->parent = $parent;
        
        return $this;
    }
    
    /**
     * @return Collection|self[]
     */
    public function getPages(): Collection
    {
        return $this->pages ?? new ArrayCollection();
    }
    
    public function addPage(self $page)
    {
        if (!$this->pages->contains($page)) {
            $this->pages[] = $page;
            $page->setParent($this);
        }
        
        return $this;
    }
    
    public function removePage(self $page)
    {
        if ($this->pages->contains($page)) {
            $this->pages->removeElement($page);
            // set the owning side to null (unless already changed)
            if ($page->getParent() === $this) {
                $page->setParent(null);
            }
        }
        
        return $this;
    }
    
    public function getContent(): ?string
    {
        return $this->content;
    }
    
    public function setContent(?string $content): self
    {
        $this->content = $content;
        
        return $this;
    }
    
    public function __toString()
    {
        return (string)$this->getName();
    }
    
    public function getSeoImage(): ?string
    {
        return $this->seoImage;
    }
    
    public function setSeoImage(?string $seoImage): self
    {
        $this->seoImage = $seoImage;
        
        return $this;
    }
    
    public function setSeoImageFile(File $image = null)
    {
        $this->seoImageFile = $image;
        
        if ($image) {
            $this->modified_at = new DateTime('now');
        }
    }
    
    public function setCardImageFile(File $image = null): void
    {
        $this->cardImageFile = $image;
        
        if ($image) {
            $this->modified_at = new DateTime('now');
        }
    }
    
    public function getSeoImageFile(): ?File
    {
        return $this->seoImageFile;
    }
    
    public function getCardImageFile(): ?File
    {
        return $this->cardImageFile;
    }
    
    public function getSeoFirstPart(): string
    {
        if (empty($this->getContent())) {
            return '';
        }
        $parts = preg_split('#<hr.*?>#', $this->getContent(), 2);
        
        return $parts[0];
    }
    
    public function getSeoSecondPart(): string
    {
        if (empty($this->getContent())) {

templates/articles/index.html.twig
{% extends 'header-less-base.html.twig' %}
{% block title page.title %}
{% block h1 page.name %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12 content">
                
                <div class="row">
                    <div class="col-md-12">
                        <h1>{{ page.name }}</h1>
                    </div>
                </div>
                <div class="row content">
                    {% for article in articles %}
                        <div class="col-lg-4 col-md-6 col-sm-12">
                            <div class="card mt-3">
                                <div class="card-header">
                                    <h3><a href="{{ article.path }}">{{ article.name }}</a></h3>
                                    <p>{{ article.createdAt|date('d.m.Y') }}</p>
                                </div>
                                <a href="{{ article.path }}">
                                    <img class="card-img" src="{{ article.cardImageUrl }}" alt="{{ article.name }}">
                                </a>
                                <div class="card-body">
                                    <div class="card-text">{{ article.cardDescription|raw }}</div>
                                </div>
                                <div class="card-footer">
                                    <div class="row justify-content-between">
                                        <a href="{{ article.path }}" class="btn btn-primary">Подробнее</a>
                                        <div class="views_counter">
                                            {{ 'articles.counter_text'|trans({'%count%': article.views}) }}
                                        </div>
                                    </div>
            
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="navigation mt-3">
                    {{ knp_pagination_render(articles) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/articles/item.html.twig
{% extends 'header-less-base.html.twig' %}
{% block title page.title %}
{% block h1 page.name %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('simple_catalog') }}
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('simple_catalog') }}
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="content">
                
                <div class="row">
                    <div class="col-md-12">
                        <h1>{{ page.name }}</h1>
                        <div class="row">
                            <div class="col-lg-2 col-md-6">{{ page.createdAt|date('d.m.Y') }}</div>
                            <div class="col-lg-2 col-md-6">
                                <div class="views_counter">
                                    {{ 'articles.counter_text'|trans({'%count%': page.views}) }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="seo-block">
                    <div class="container">
                        {{ page.content|raw }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if page.products|length > 0 %}
        <div class="container">
            <h2 class="text-center">Товары к статье:</h2>
            {{ include('modules/recommended_products.html.twig', {items: page.products, hideCatalog: true}) }}
        </div>
    {% endif %}
{% endblock %}