src/Entity/Geo.php
<?php

namespace App\Entity;

use App\Entity\Contracts\HasCatalogSettingsInterface;
use App\Entity\Traits\CatalogSettingsTrait;
use App\Model\GeoProduct\AbstractGeoProduct;
use App\Model\GeoProduct\RulonnyieShtoryiGeoProduct;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\EntityListeners({"App\EntityListener\GeoListener"})
 */
abstract class Geo extends Page implements HasCatalogSettingsInterface
{
    
    use CatalogSettingsTrait;
    
    public const TYPE = 'geo';
    /**
     * @var AbstractGeoProduct
     */
    protected $geoProduct;
    
    /**
     * @return AbstractGeoProduct
     */
    public function getGeoProduct(): AbstractGeoProduct
    {
        if (null === $this->geoProduct) {
            $this->geoProduct = AbstractGeoProduct::create($this->getGeoProductType());
        }
        
        return $this->geoProduct;
    }
    
    public function getCardHeader(): string
    {
        return $this->getH1() . ' цена';
    }
    
    public function getCardDescription(): string
    {
        return sprintf('<p><span><b>Материал:</b> ткань, алюминий, пластик, дерево.</span> <span><b>Цвет:</b> на выбор.</span> <span><b>Размеры:</b> стандартные и под заказ</span> <span><b>Тип:</b> горизонтальные и вертикальные.</span> <span><b>Виды:</b> алюминиевые, пластиковые, деревянные, тканевые.</span> <span><b>Помещения:</b>&nbsp;терраса&nbsp;</span><span><b>Управление:</b> механическое и автоматическое</span> <span><b>Срок изготовления и установки:</b> 2-7 дней (зависит от сложности и объема).</span> <span><b>Замер:</b> бесплатный (при оформлении и оплате заказа).</span> <span><b>Доставка и установка %s:</b> в $city_and_region_prepositional.</span> <span>Возможна доставка и установка по России</span></p>',
            $this->getGeoProduct()->getNameGenitive());
    }
    
    public function getCardImageUrl(): string
    {
        return $this->getGeoProduct()->getCardImage();
    }
    
    public function getTypeFilter(): string
    {
        return $this->getGeoProductType() === RulonnyieShtoryiGeoProduct::TYPE ? '133' : '86,132,178';
    }
    
    public function isShowCatalog(): bool
    {
        return $this instanceof City
               || in_array($this->getUri(), ['moskovskoy-oblasti', 'rulonnyie-shtoryi/moskovskoy-oblasti']);
    }
    
    public function getBaseCatalogUri(): string
    {
        return $this->getGeoProductType() === RulonnyieShtoryiGeoProduct::TYPE ? 'rulonnyie-shtoryi' : 'vertikalnye-zhalyuzi-na-okna';
    }
}

src/Entity/Page.php
<?php

namespace App\Entity;

use App\Entity\Contracts\HasExamplesInterface;
use App\Entity\Contracts\TurboPageInterface;
use App\Entity\Traits\RatingTrait;
use App\Model\GeoProduct\RulonnyieShtoryiGeoProduct;
use App\Model\GeoProduct\ZhalyuziGeoProduct;
use DateTime;
use DateTimeImmutable;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PageRepository")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="page_type", type="string")
 * @ORM\DiscriminatorMap({
 *     District::TYPE = "District",
 *     Metro::TYPE = "Metro",
 *     City::TYPE = "City",
 *     Product::TYPE = "Product",
 *     Catalog::TYPE = "Catalog",
 *     Simple::TYPE = "Simple",
 *     Location::TYPE = "Location",
 *     Roman::TYPE = "Roman",
 *     Roll::TYPE = "Roll",
 *     Markiz::TYPE = "Markiz",
 *     Geo::TYPE = "Geo",
 *     Calculator::TYPE = "Calculator",
 *     Article::TYPE = "Article",
 * })
 * @ORM\Table(indexes={
 *     @ORM\Index(name="IDX_NAME_FULLTEXT", columns={"name"}, flags={"fulltext"})
 * })
 * @Vich\Uploadable
 * @ORM\HasLifecycleCallbacks()
 */
abstract class Page implements TurboPageInterface, HasExamplesInterface
{
    use RatingTrait;
    
    const MIN_RATING_VALUE = 4.7;
    const MAX_RATING_VALUE = 4.9;
    const MIN_RATING_COUNT = 8;
    const MAX_RATING_COUNT = 35;
    const DEFAULT_WORK_EXAMPLES_LIMIT = 3;
    
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;
    
    /**
     * @ORM\Column(type="string", length=255)
     */
    protected ?string $name = '';
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected ?string $h1 = null;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected ?string $nameGenitive = null;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected ?string $nameNominative = null;
    
    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $uri;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $title = null;
    
    /**
     * @ORM\Column(type="text", length=255, nullable=true)
     */
    protected $description = null;
    
    /**
     * @ORM\Column(type="boolean")
     */
    protected $published = 1;
    
    /**
     * @ORM\Column(type="boolean", options={"default": 0})
     */
    protected $yml = false;
    
    /**
     * @ORM\Column(type="boolean", options={"default": 0})
     */
    protected $turbo = false;
    
    /**
     * @ORM\Column(type="boolean", options={"default": 1})
     */
    protected $showSeoText = true;
    
    /**
     * @ORM\Column(type="datetime")
     */
    protected $created_at;
    
    /**
     * @ORM\Column(type="datetime")
     */
    protected $modified_at;
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Page", inversedBy="pages")
     */
    protected ?Page $parent;
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Page", mappedBy="parent")
     * @ORM\OrderBy({"ordering" = "ASC", "id" = "ASC",})
     */
    protected $pages;
    
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $content;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $seoImage;
    
    /**
     * @Vich\UploadableField(mapping="seo_images", fileNameProperty="seoImage")
     * @var File
     */
    protected $seoImageFile;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $ourWorksFolder;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $cardImage;
    
    /**
     * @Vich\UploadableField(mapping="card_images", fileNameProperty="cardImage")
     * @var File
     */
    protected $cardImageFile;
    
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $cardDescription;
    
    /**
     * @var string
     * @ORM\Column(type="string",options={"default": App\Model\GeoProduct\ZhalyuziGeoProduct::TYPE})
     */
    protected $geoProductType = ZhalyuziGeoProduct::TYPE;
    /**
     * @ORM\Column(type="json", nullable=true)
     */
    protected ?array $popularCategories = [];
    
    /**
     * @ORM\ManyToMany(targetEntity=WorkExample::class, mappedBy="pages")
     * @ORM\OrderBy({"position" = "ASC"})
     */
    private Collection $workExamplesOfPage;
    
    /**
     * @ORM\Column(type="json", nullable=true)
     */
    protected ?array $settings = [];
    
    /**
     * @ORM\Column(type="integer",nullable=false, options={"default": 0})
     */
    protected int $ordering = 0;
    
    /**
     * @ORM\Column(nullable=false, options={"default": 0.7})
     */
    protected float $priority = 0.7;
    
    /**
     * @ORM\Column(type="json", nullable=true)
     */
    protected ?array $faq = [];
    
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected ?string $faqTitle = null;
    
    public function __construct()
    {
        $this->created_at  = new DateTimeImmutable();
        $this->modified_at = new DateTimeImmutable();
        $this->pages       = new ArrayCollection();
        $this->generateRatingAndCount();
        $this->workExamplesOfPage = new ArrayCollection();
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }
    
    public function getName(): ?string
    {
        return $this->name;
    }
    
    public function setName(string $name)
    {
        $this->name = $name;
        
        return $this;
    }
    
    public function getUri(): ?string
    {
        return $this->uri;
    }
    
    public function getPath(): string
    {
        if ($this->uri === '/') {
            return '/';
        }
        
        return '/' . $this->uri . '/';
    }
    
    public function setUri(string $uri)
    {
        $this->uri = trim($uri);
        
        return $this;
    }
    
    public function setPath(string $path)
    {
        return $this->setUri($path);
    }
    
    public function getTitle(): ?string
    {
        return $this->title;
    }
    
    public function setTitle(?string $title)
    {
        $this->title = $title;
        
        return $this;
    }
    
    public function getDescription(): ?string
    {
        return $this->description;
    }
    
    public function setDescription(?string $description)
    {
        $this->description = $description;
        
        return $this;
    }
    
    public function getPublished(): ?bool
    {
        return $this->published;
    }
    
    public function setPublished(bool $published)
    {
        $this->published = $published;
        
        return $this;
    }
    
    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->created_at;
    }
    
    public function setCreatedAt(DateTimeInterface $created_at): Page
    {
        $this->created_at = $created_at;
        
        return $this;
    }
    
    public function getModifiedAt(): ?DateTimeInterface
    {
        return $this->modified_at;
    }
    
    public function setModifiedAt(DateTimeInterface $modified_at)
    {
        $this->modified_at = $modified_at;
        
        return $this;
    }
    
    public function getParent()
    {
        return $this->parent;
    }
    
    public function setParent(?self $parent)
    {
        $this->parent = $parent;
        
        return $this;
    }
    
    /**
     * @return Collection|self[]
     */
    public function getPages(): Collection
    {
        return $this->pages ?? new ArrayCollection();
    }
    
    public function addPage(self $page)
    {
        if (!$this->pages->contains($page)) {
            $this->pages[] = $page;
            $page->setParent($this);
        }
        
        return $this;
    }
    
    public function removePage(self $page)
    {
        if ($this->pages->contains($page)) {
            $this->pages->removeElement($page);
            // set the owning side to null (unless already changed)
            if ($page->getParent() === $this) {
                $page->setParent(null);
            }
        }
        
        return $this;
    }
    
    public function getContent(): ?string
    {
        return $this->content;
    }
    
    public function setContent(?string $content): self
    {
        $this->content = $content;
        
        return $this;
    }
    
    public function __toString()
    {
        return (string)$this->getName();
    }
    
    public function getSeoImage(): ?string
    {
        return $this->seoImage;
    }
    
    public function setSeoImage(?string $seoImage): self
    {
        $this->seoImage = $seoImage;
        
        return $this;
    }
    
    public function setSeoImageFile(File $image = null)
    {
        $this->seoImageFile = $image;
        
        if ($image) {
            $this->modified_at = new DateTime('now');
        }
    }
    
    public function setCardImageFile(File $image = null): void
    {
        $this->cardImageFile = $image;
        
        if ($image) {
            $this->modified_at = new DateTime('now');
        }
    }
    
    public function getSeoImageFile(): ?File
    {
        return $this->seoImageFile;
    }
    
    public function getCardImageFile(): ?File
    {
        return $this->cardImageFile;
    }
    
    public function getSeoFirstPart(): string
    {
        if (empty($this->getContent())) {
            return '';
        }
        $parts = preg_split('#<hr.*?>#', $this->getContent(), 2);
        
        return $parts[0];
    }
    
    public function getSeoSecondPart(): string
    {
        if (empty($this->getContent())) {

templates/modules/_advantages.html.twig
<!--начало блока ПРЕИМУЩЕСТВА С ВИДИОФОНОМ-->
<div {{ lazy_load_bg('/img/3.jpg',['block4']) }}>
    
    <div class="preim-wrap">
        <div class="container">
            <h2 class="zag1">Преимущества</h2>
            <div class="row">
                <div class="col-xl-3 col-lg-4 col-md-6 panim">
                    <div class="preim preim1">
                        <div class="preim-img"><img {{ lazy_load('/img/preim/1.png') }} alt="*"></div>
                        <div class="preim-zag">Быстрый монтаж</div>
                        <div class="preim-text">Изготовление и установка {{ page.nameGenitive|default('жалюзи') }} за 2-5 рабочих дня.</div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4 col-md-6 panim">
                    <div class="preim preim1">
                        <div class="preim-img"><img {{ lazy_load('/img/preim/2.png') }} alt="*"></div>
                        <div class="preim-zag">Бесплатный замер</div>
                        <div class="preim-text">Выезд замерщика на дом (в пределах МКАД) с 9.00 до 18.00 - бесплатно, в случае заказа!</div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4 col-md-6 panim">
                    <div class="preim preim1">
                        <div class="preim-img"><img {{ lazy_load('/img/preim/3.png') }} alt="*"></div>
                        <div class="preim-zag">Скидки от 7%</div>
                        <div class="preim-text">Предоставляем лучшие цены в $city_and_region_prepositional.</div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4 col-md-6 panim">
                    <div class="preim preim1">
                        <div class="preim-img"><img {{ lazy_load('/img/preim/4.png') }} alt="*"></div>
                        <div class="preim-zag">Более 10 лет на рынке</div>
                        <div class="preim-text">Собственное производство и огромный опыт.</div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4 col-md-6 panim">
                    <div class="preim preim1">
                        <div class="preim-img"><img {{ lazy_load('/img/preim/5.png') }} alt="*"></div>
                        <div class="preim-zag">Гарантия 2 года</div>
                        <div class="preim-text">На все {{ page.nameNominative|default('жалюзи') }} мы предоставляем гарантию.</div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4 col-md-6 panim">
                    <div class="preim preim1">
                        <div class="preim-img"><img {{ lazy_load('/img/preim/6.png') }} alt="*"></div>
                        <div class="preim-zag">Работаем честно</div>
                        <div class="preim-text">Гарантируем качество материалов и изделий.</div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4 offset-lg-2 offset-xl-0 col-md-6 panim">
                    <div class="preim preim1">
                        <div class="preim-img"><img {{ lazy_load('/img/preim/7.png') }} alt="*"></div>
                        <div class="preim-zag">Работаем 24/7</div>
                        <div class="preim-text">Выезд замерщика и монтаж осуществляется круглосуточно и без выходных.</div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4 col-md-6 panim">
                    <div class="preim preim1">
                        <div class="preim-img"><img {{ lazy_load('/img/preim/8.png') }} alt="*"></div>
                        <div class="preim-zag">До 150 км от Москвы</div>
                        <div class="preim-text">Доставка и монтаж {{ page.nameGenitive|default('жалюзи') }} по всей Москве и области.</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--конец блока ПРЕИМУЩЕСТВА С ВИДИОФОНОМ-->

templates/modules/_catalog.html.twig
<div class="container products">
    {% for item in items %}
        <div class="product">
            <a href="/{{ item.uri }}/">
                <div class="product__image_wrapper">
                    <img {{ lazy_load(asset(item.cardImageUrl) | imagine_filter('catalog_thumb')) }}
                            alt="{{ item.name }}">
                </div>
            </a>
            <div class="product__name">
                <a href="/{{ item.uri }}/">{{ item.name }}</a>
            </div>
            <div class="product__price">
                {% if area??false %}
                    {{ item.price }} руб/м2
                {% else %}
                    от {{ item.price }} руб
                {% endif %}
        
            </div>
            <div class="d-flex justify-content-center">
                <button class="mbtn mbtn_orange js-modal-open" data-title="Рассчитать">Рассчитать</button>
            </div>

        </div>
    {% endfor %}
</div>

templates/modules/_catalog_complex.html.twig
<div class="products">
    {% for item in items %}
        <div class="product">
            <a href="/{{ item.uri }}/">
                {% if needWrapper ?? true %}
                <div class="product__image_wrapper">
                    {% endif %}
                    <img {{ lazy_load(asset(item.cardImageUrl) | imagine_filter('catalog_thumb')) }}
                            alt="{{ item.name }}">
                    {% if needWrapper ?? true %}
                </div>
                {% endif %}
        
            </a>
            <div class="product__name">
                <a href="/{{ item.uri }}/">{{ item.name }}</a>
            </div>
            <div class="product__price">
                {{ min_price(item, false, true) }}
            </div>
            {{ include('modules/_callback_buttons.html.twig') }}
        </div>
    {% endfor %}
</div>

templates/modules/_modal_callback.html.twig
<div class="cd-user-modal" id="modal-callback">
    <div class="overlay"></div>
    <div class="cd-user-modal-container">
        <div id="cd-raschet" class="is-selected">
            <div class="modal_close">×</div>
            <form class="cd-form phone_callback" method="POST" action="{{ path('mail.callback_consultation') }}">
                <div class="form-body">
                    <span class="modal-title">Заказать звонок:</span>

                    <p class="fieldset">
                        <label class="image-replace cd-name" for="modal-form-name">Ваше имя:</label>
                        <input
                                class="full-width has-padding has-border"
                                id="modal-form-name"
                                name="name"
                                type="text"
                                placeholder="Ваше имя"
                                required=""
                        >
                    </p>

                    <p class="fieldset">
                        <label class="image-replace cd-phone" for="modal-form-phone">Телефон</label>
                        <input
                                class="full-width has-padding has-border phone-field"
                                id="modal-form-phone"
                                name="phone"
                                type="tel"
                                placeholder="Телефон"
                                required=""
                        >
                    </p>
                    {{ include('modules/agreement-checkbox.html.twig') }}
                    <p class="fieldset">
                        <button class="full-width form-submit js-submit-callback-form">ОТПРАВИТЬ</button>
                    </p>

                    <input type="hidden" name="token" value="{{ csrf_token('consultation') }}" />
                </div>
            </form>
        </div>
    </div> <!-- cd-user-modal-container -->
</div>

templates/modules/_modal_success.html.twig
<div class="cd-user-modal" id="modal-success">
    <div class="overlay"></div>
    <div class="cd-user-modal-container">
        <div id="cd-raschet" class="is-selected">
            <div class="success_send_popup_body">
                <div class="success_send_popup_img">
                    <div class="sa-icon sa-success animate">
                        <span class="sa-line sa-tip animateSuccessTip"></span>
                        <span class="sa-line sa-long animateSuccessLong"></span>
                        <div class="sa-placeholder"></div>
                        <div class="sa-fix"></div>
                    </div>
                </div>
                <h2>Спасибо за заявку!</h2>
                <p>Наш менеджер свяжется с вами в самое ближайшее время!</p>
                <div class="success_send_down">
                    <button class="mfp-close modal_close js-submit-success">ОК</button>
                </div>
            </div>
        </div>
    </div> <!-- cd-user-modal-container -->
</div>

templates/modules/_our_works.html.twig
{% if page.ourWorksFolder %}
    <div class="works">
        <div class="container container2">
            <div class="zag">Примеры работ:</div>
            {{ swiper_slider(page.ourWorksFolder) }}
        </div>
    </div>
{% endif %}

<!--конец ПРИМЕРЫ РАБОТ(СЛАЙДЕР)-->

templates/modules/_seo_block.html.twig
{% if page.seoFirstPart and page.showSeoText and isMainDomain %}
    <div class="seo-block">
        <div class="container">
            <div class="row">
                <div class="seo-left col-md-6">
                    {{ page.seoFirstPart|raw }}
                </div>
                <div class="seo-right col-md-6 "><img src="{{ vich_uploader_asset(page,'seoImageFile') }}" alt="*"></div>
    {% if page.seoSecondPart %}
                <div class="seo-left col-12">
                    <div class="seo-text-none">
                       {{ page.seoSecondPart|raw }}
                    </div>
                    <div class="seo-btn mbtn">Читать далее</div>
                </div>
    {% endif %}
            </div>
        </div>
    </div>
{% endif %}

templates/modules/breadcrumbs.html.twig
<div class="container-fluid">
    <ul class="breadcrumps__block mt-2">
        {% for item in items %}
            {% if not loop.first %}
                <li class="breadcrumps__list">></li>
            {% endif %}
            
            <li class="breadcrumps__list">
                {% if loop.last %}
                    <span>{{ item.name }}</span>
                {% else %}
                    <a href="{{ item.link }}">{{ item.name }}</a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
</div>

templates/modules/domain_modal.html.twig
<div class="cd-user-modal" id="modal-domain">
    <div class="overlay"></div>
    <div class="cd-user-modal-container">
        <div id="cd-raschet" class="is-selected">
            <div class="modal_close">×</div>
            <div class="domain_modal">
                <div class="domain_modal__title">Выберите Ваш город</div>
                <div class="domain_modal__cities">
                    {% for item in items %}
                        <div>
                            <a
                                    href="{{ item.mainPageUrl }}"
                                    class="{{ item is same as currentSubDomain ? 'cities_current' : '' }}"
                            >{{ item.cityNominative }}</a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div> <!-- cd-user-modal-container -->
</div>

templates/modules/domain_modal_trigger.html.twig
<div class="js-modal-domain-open modal-domain-open">
    <div class="modal-domain-open__icon"></div>
    <div class="modal-domain-open__title">{{ currentSubDomain.cityNominative }}</div>
</div>

templates/modules/link_selector.html.twig
{% set selected = placeholder %}
{% for name, link in options %}
    {% if link in app.request.requestUri %}
        {% set selected = name %}
    {% endif %}
{% endfor %}

<div class="link_selector">
    <button class="link_selector__selected">{{ selected }}</button>
    <div class="link_selector__options">
        <ul>
            {% for name, link in options %}
                <li {{ name != selected ? 'class = "not-active"' }}>
                    <a href="{{ link }}#content">{{ name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

templates/modules/rating.html.twig
<!--Блок РЕЙТИНГИ начало-->
{% set ratingItems = [
    {
        'link' : 'https://yandex.ru/maps/org/masterskaya_zhalyuzi/199082594181/',
        'img': 'img/rating/logo-yandex.png',
        'alt': 'Yandex',
        'stars': 5,
        'rating': 5.0
    },
    {
        'link' : 'https://zoon.ru/msk/building/masterskaya_zhalyuzi_torgovo-servisnaya_kompaniya/',
        'img': 'img/rating/logo-zoon.png',
        'alt': 'Zoon.ru',
        'stars': 4.5,
        'rating': 4.8
    },
    {
        'link' : 'https://goo.gl/maps/RomdL3CkncjsZyr47',
        'img': 'img/rating/logo-google.png',
        'alt': 'Google',
        'stars': 5,
        'rating': 5
    },
    {
        'link' : 'https://go.2gis.com/i6gws',
        'img': 'img/rating/logo-2gis.png',
        'alt': '2 Gis',
        'stars': 5,
        'rating': 5
    },
] %}
<div class="rating">
    <div class="container container2">
        <div class="zag">Независимые отзывы:</div>
        {{ show_schema|default(false) ? include('modules/rating_schema.html.twig') }}
        <div class="row">
            {% for ratingItem in ratingItems %}
                <div class="col-lg-3 col-6 scroll-item">
                    <a target="_blank" rel="nofollow" href="{{ ratingItem.link }}">
                        <div class="rating-card">
                            <div class="img">
                                <img {{ lazy_load(asset(ratingItem.img)) }} alt="{{ ratingItem.alt }}">
                            </div>
                            <div class="text">
                                <span>рейтинг</span>
                                {{ stars(ratingItem.stars) }}
                                <b>{{ ratingItem.rating }} из 5</b>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
<!--Блок РЕЙТИНГИ Конец-->

templates/modules/rating_schema.html.twig
<div class="rating_schema hide-mobile">
    <meta itemprop="worstRating" content="1">
    <div
            class="mt-1 rating_wrapper"
            itemprop="aggregateRating"
            itemscope="itemscope"
            itemtype="http://schema.org/AggregateRating"
    >
        <div class="rating-box mr-2">
            {{ stars(4.5) }}
        </div>

        <div class="rating-details">
          <span class="mr-1">
                <strong>
                    <span itemprop="ratingValue">{{ page.ratingValue }}</span>
                </strong>&nbsp;
                <span class="text-muted">из&nbsp;
                    <span itemprop="bestRating">5</span>
                </span>
            </span>
            <em class="small text-muted">
                <span itemprop="ratingCount">{{ page.ratingCount }}</span>&nbsp;оценок
            </em>
        </div>
        <div class="rating-details text-muted ml-2"> Рейтинг составлялся по отзывам от клиентов.</div>
    </div>
</div>

templates/modules/recommended-main-page.html.twig
<div class="container hide-mobile">
    <h2>Рекомендуемые жалюзи:</h2>
    {{ recommendedMainPage() }}
</div>