src/Entity/Geo.php
<?php

namespace App\Entity;

use App\Entity\Contracts\HasCatalogSettingsInterface;
use App\Entity\Traits\CatalogSettingsTrait;
use App\Model\GeoProduct\AbstractGeoProduct;
use App\Model\GeoProduct\RulonnyieShtoryiGeoProduct;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\EntityListeners({"App\EntityListener\GeoListener"})
 */
abstract class Geo extends Page implements HasCatalogSettingsInterface
{
    
    use CatalogSettingsTrait;
    
    public const TYPE = 'geo';
    /**
     * @var AbstractGeoProduct
     */
    protected $geoProduct;
    
    /**
     * @return AbstractGeoProduct
     */
    public function getGeoProduct(): AbstractGeoProduct
    {
        if (null === $this->geoProduct) {
            $this->geoProduct = AbstractGeoProduct::create($this->getGeoProductType());
        }
        
        return $this->geoProduct;
    }
    
    public function getCardHeader(): string
    {
        return $this->getH1() . ' цена';
    }
    
    public function getCardDescription(): string
    {
        return sprintf('<p><span><b>Материал:</b> ткань, алюминий, пластик, дерево.</span> <span><b>Цвет:</b> на выбор.</span> <span><b>Размеры:</b> стандартные и под заказ</span> <span><b>Тип:</b> горизонтальные и вертикальные.</span> <span><b>Виды:</b> алюминиевые, пластиковые, деревянные, тканевые.</span> <span><b>Помещения:</b>&nbsp;терраса&nbsp;</span><span><b>Управление:</b> механическое и автоматическое</span> <span><b>Срок изготовления и установки:</b> 2-7 дней (зависит от сложности и объема).</span> <span><b>Замер:</b> бесплатный (при оформлении и оплате заказа).</span> <span><b>Доставка и установка %s:</b> в $city_and_region_prepositional.</span> <span>Возможна доставка и установка по России</span></p>',
            $this->getGeoProduct()->getNameGenitive());
    }
    
    public function getCardImageUrl(): string
    {
        return $this->getGeoProduct()->getCardImage();
    }
    
    public function getTypeFilter(): string
    {
        return $this->getGeoProductType() === RulonnyieShtoryiGeoProduct::TYPE ? '133' : '86,132,178';
    }
    
    public function isShowCatalog(): bool
    {
        return $this instanceof City
               || in_array($this->getUri(), ['moskovskoy-oblasti', 'rulonnyie-shtoryi/moskovskoy-oblasti']);
    }
    
    public function getBaseCatalogUri(): string
    {
        return $this->getGeoProductType() === RulonnyieShtoryiGeoProduct::TYPE ? 'rulonnyie-shtoryi' : 'vertikalnye-zhalyuzi-na-okna';
    }
}

src/Entity/Location.php
<?php

namespace App\Entity;

use App\Entity\Contracts\HasCatalogSettingsInterface;
use App\Entity\Traits\CatalogSettingsTrait;
use App\Model\Admin\LocationImport;
use App\Model\GeoProduct\RulonnyieShtoryiGeoProduct;
use App\Model\GeoProduct\ZhalyuziGeoProduct;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LocationRepository")
 * @ORM\EntityListeners({"App\EntityListener\LocationListener"})
 */
class Location extends Page implements HasCatalogSettingsInterface
{
    
    use CatalogSettingsTrait;
    
    public const TYPE = 'location';
    
    /**
     * @ORM\ManyToOne(targetEntity=Catalog::class, inversedBy="locations")
     */
    private ?Catalog $baseCatalog;
    
    public function getCardImgFolder()
    {
        return 'img/location/';
    }
    
    public function getType(): ?Type
    {
        $parent = $this->getParent();
        if ($parent && $parent instanceof Catalog) {
            return $parent->getType();
        }
        
        return null;
    }
    
    public function getDescription(): ?string
    {
        if (!empty(parent::getDescription())) {
            return parent::getDescription();
        }
        
        return sprintf('%s купить недорого в $city_prepositional. ✅ Выезд и замер бесплатно! ✅ Изготовление жалюзи с установкой за 1-4 дня. ✅ Гарантия 2 года. ⭐ %s по низким ценам в интернет магазине «Мастерская жалюзи» ☎ 8-800-775-72-38.',
            $this->getName(), $this->getName());
    }
    
    public function getTurboContentTemplate(): string
    {
        return 'turbo/locations/content.html.twig';
    }
    
    public function getGeoProductType(): string
    {
        return str_starts_with($this->getUri(), 'rulonnyie-shtoryi')
            ? RulonnyieShtoryiGeoProduct::TYPE
            : ZhalyuziGeoProduct::TYPE;
    }
    
    public function getPrice(): string
    {
        return $this->price;
    }
    
    public function setPrice(string $price)
    {
        $this->price = $price;
    }
    
    public function getCalcLink(): ?string
    {
        return '/' . $this->getBaseCatalogUri() . '/kalkulyator/';
    }
    
    public function getBaseCatalogUri(): string
    {
        return $this->getBaseCatalog()?->getUri();
    }
    
    public function getBaseCatalog(): ?Catalog
    {
        return $this->baseCatalog;
    }
    
    public function setBaseCatalog(?Catalog $baseCatalog): self
    {
        $this->baseCatalog = $baseCatalog;
        
        return $this;
    }
    
    public function generateDescription(): self
    {
        $this->description = sprintf('%s купить недорого в $city_prepositional. ⭐ Выезд и замер бесплатно! ✅ Изготовление жалюзи с установкой за 1-4 дня. ✅ Гарантия 2 года. ⭐ %s по низким ценам в интернет магазине «Мастерская жалюзи» ☎ 8-800-775-72-38.',
            $this->getH1(), $this->getName());
        
        return $this;
    }
    
    public function generateTitle(): self
    {
        $this->title = sprintf('%s купить в $city_prepositional с установкой. Каталог и цены', $this->getName());
        
        return $this;
    }
    
    public function generateCardDescription(LocationImport $locationImport, string $locationName): self
    {
        $this->cardDescription = sprintf(
            '<p><span><b>Материал:</b> %s</span> <span><b>Цвет:</b> на выбор.</span> <span><b>Размеры:</b> стандартные и под заказ</span> <span><b>Тип:</b> %s</span> <span><b>Виды:</b> %s</span> <span><b>Помещения:</b> %s</span><span><b>Управление:</b> механическое и автоматическое</span> <span><b>Срок изготовления и установки:</b> 2-7 дней (зависит от сложности и объема).</span> <span><b>Замер:</b> бесплатный (при оформлении и оплате заказа).</span> <span><b>Доставка и установка жалюзи:</b> в $city_and_region_prepositional.</span> <span>Возможна доставка и установка по России</span></p>
',
            $locationImport->getMaterials(),
            $locationImport->getType(),
            $locationImport->getSubTypes(),
            $locationName
        );
    
        return $this;
    }
    
    public function getShortName(): string
    {
        return $this->name;
    }
    
    public function getFilterPlaceholder(): string
    {
        return $this->getBaseCatalog()?->getFilterPlaceholder() ?? $this->getName();
    }
}

templates/turbo/advantages.html.twig
<!--начало блока ПРЕИМУЩЕСТВА С ВИДИОФОНОМ-->
<div>

    <div>
        <div>
            <h2>Преимущества</h2>
            <div>
                <div>
                    <div>
                        <div><img src="{{ app.request.schemeAndHttpHost }}/img/preim/1.png" alt="*" /></div>
                        <div>Изготовление и установка жалюзи за 2-5 рабочих дня.</div>
                    </div>
                </div>
                <div>
                    <div>
                        <div><img src="{{ app.request.schemeAndHttpHost }}/img/preim/2.png" alt="*"></div>
                        <div>Выезд замерщика на дом (в пределах МКАД) с 9.00 до 18.00 - бесплатно, в случае заказа!</div>
                    </div>
                </div>
                <div>
                    <div>
                        <div><img src="{{ app.request.schemeAndHttpHost }}/img/preim/3.png" alt="*"></div>
                        <div>Скидки от 7% при заказе на сайте</div>
                    </div>
                </div>
                <div>
                    <div>
                        <div><img src="{{ app.request.schemeAndHttpHost }}/img/preim/4.png" alt="*"></div>
                        <div>Собственное производство и огромный опыт.</div>
                    </div>
                </div>
                <div>
                    <div>
                        <div><img src="{{ app.request.schemeAndHttpHost }}/img/preim/5.png" alt="*"></div>
                        <div>На все жалюзи мы предоставляем гарантию 2 года</div>
                    </div>
                </div>
                <div>
                    <div>
                        <div><img src="{{ app.request.schemeAndHttpHost }}/img/preim/6.png" alt="*"></div>
                        <div>Гарантируем качество материалов и изделий. Работаем честно</div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4 offset-lg-2 offset-xl-0 col-md-6">
                    <div>
                        <div><img src="{{ app.request.schemeAndHttpHost }}/img/preim/7.png" alt="*"></div>
                        <div>Выезд замерщика и монтаж осуществляется круглосуточно и без выходных.</div>
                    </div>
                </div>
                <div>
                    <div>
                        <div><img src="{{ app.request.schemeAndHttpHost }}/img/preim/8.png" alt="*"></div>
                        <div>Доставка и монтаж по всей Московской области. До 150 км от Москвы</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--конец блока ПРЕИМУЩЕСТВА С ВИДИОФОНОМ-->

templates/turbo/callback-buttons-with-direct-link.html.twig
<button
        formaction="tel:{{ phone }}"
        data-background-color="blue"
        data-color="white"
        data-turbo="true"
        data-primary="true"
>
    Рассчитать
</button>

<button
        formaction="{{ app.request.schemeAndHttpHost }}{{ page.path }}"
        data-background-color="blue"
        data-color="white"
        data-turbo="false"
        data-primary="true"
>
    Посмотреть образцы
</button>

<button
        formaction="tel:{{ phone }}"
        data-background-color="blue"
        data-color="white"
        data-turbo="true"
        data-primary="true"
>
    Консультация
</button>

templates/turbo/callback-buttons.html.twig
{% set buttons = ['Рассчитать', 'Консультация'] %}
{% for button in buttons %}
    <button
            formaction="tel:{{ phone }}"
            data-background-color="blue"
            data-color="white"
            data-turbo="false"
            data-primary="true"
    >
        {{ button }}
    </button>
{% endfor %}

templates/turbo/callback-corner.html.twig
<div data-block="widget-feedback" data-title="Обратная связь" data-stick="right">
    <div data-type="call" data-url="{{ phone }}"></div>
    <div data-type="whatsapp" data-url="https://wa.me/{{ get_config_cached('whatsapp.phone') }}"></div>
</div>

templates/turbo/calс-button.html.twig
{% if page.calcLink is not empty %}
    <button
            formaction="{{ app.request.schemeAndHttpHost }}{{ page.calcLink }}"
            data-background-color="blue"
            data-color="white"
            data-turbo="false"
            data-primary="true"
    >
        Калькулятор
    </button>
{% endif %}

templates/turbo/card.html.twig
<div class="card">
    <h2>{{ page.cardHeader }}</h2>
    <img src="{{ app.request.schemeAndHttpHost }}{{ page.cardImageUrl }}" alt="*">
    {{ page.textComputed|raw }}
    <hr />
    <h3><b>Цена от {{ discounted_price(catalog_min_price('vertikalnye-zhalyuzi-na-okna')) }} руб/м2</b></h3>
</div>

templates/turbo/clients.html.twig
<h2>Наши клиенты</h2>

<div data-block="slider" data-view="landscape">
    {% for i in 1..5 %}
        <figure>
            <img src="{{ app.request.schemeAndHttpHost ~ '/img/our-clients/'~i~'.png' }}" alt="*"/>
        </figure>
    {% endfor %}
</div>

templates/turbo/content.html.twig
{% set phone = '8 (495) 984-38-48' %}

{% include 'turbo/why-us.html.twig' %}
{% include 'turbo/rating.html.twig' %}
{% include 'turbo/card.html.twig' %}
{% include 'turbo/callback-buttons.html.twig' %}
{% include 'turbo/calс-button.html.twig' %}
{% include 'turbo/clients.html.twig' %}

{% include 'turbo/callback-corner.html.twig' %}

templates/turbo/rating-yandex.html.twig
<div class="rating">
    <h2>Независимые отзывы:</h2>
    <a href="https://yandex.ru/maps/org/masterskaya_zhalyuzi/199082594181/?ll=37.631900%2C55.812373&z=14"
       target="_blank">
        <img src="{{ app.request.schemeAndHttpHost }}/img/otzyv.png" alt="*">
    </a>
</div>

templates/turbo/rating.html.twig
{% set ratingItems = [
    {
        'link' : 'https://yandex.ru/maps/org/masterskaya_zhalyuzi/199082594181/',
        'img': 'img/rating/logo-yandex.png',
        'alt': 'Yandex',
        'stars': 5,
        'rating': 5.0
    },
    {
        'link' : 'https://zoon.ru/msk/building/masterskaya_zhalyuzi_torgovo-servisnaya_kompaniya/',
        'img': 'img/rating/logo-zoon.png',
        'alt': 'Zoon.ru',
        'stars': 45,
        'rating': 4.8
    },
    {
        'link' : 'https://goo.gl/maps/RomdL3CkncjsZyr47',
        'img': 'img/rating/logo-google.png',
        'alt': 'Google',
        'stars': 5,
        'rating': 5
    },
    {
        'link' : 'https://go.2gis.com/i6gws',
        'img': 'img/rating/logo-2gis.png',
        'alt': '2 Gis',
        'stars': 5,
        'rating': 5
    },
] %}
<div class="rating">
    <div class="container container2">
        <h2>Независимые отзывы:</h2>
        <div class="row justify-content-xs-center">
            {% for ratingItem in ratingItems %}
                <div class="col-lg-3 col-6">
                    <a target="_blank" href="{{ ratingItem.link }}">
                        <div class="rating-card">
                            <div class="img">
                                <img src="{{ app.request.schemeAndHttpHost }}{{ asset(ratingItem.img) }}"  alt="{{ ratingItem.alt }}">
                            </div>
                            <div class="text">
                                <img src="{{ app.request.schemeAndHttpHost }}/img/rating/stars-{{ ratingItem.stars }}.jpg" alt="{{ ratingItem.rating }}">
                                <b>{{ ratingItem.rating }} из 5</b>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

templates/turbo/why-us.html.twig
<div class="offer">
    <p>
        &#9989;
        Гарантия 2 года
    </p>
    <p>
        &#9989;
        Бесплатный выезд и замер
    </p>
    <p>
        &#9989;
        Изготовление и установка 2-5 рабочих дня
    </p>
</div>