src/Entity/Catalog.php
<?php

namespace App\Entity;

use App\Entity\Contracts\HasCatalogSettingsInterface;
use App\Entity\Traits\CatalogCalcTrait;
use App\Entity\Traits\CatalogSettingsTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CatalogRepository")
 */
class Catalog extends Page implements HasCatalogSettingsInterface
{
    public const SEO_TYPE_PREMIUM = 'premium';
    public const SEO_TYPE_NO_DRILL = 'no-drill';
    public const SEO_TYPE_WITH_INSTALLATION = 'with-installation';
    public const SEO_TYPE_FOR_ORDER = 'for-order';
    
    use CatalogCalcTrait;
    use CatalogSettingsTrait;
    
    public const TYPE = 'catalog';
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $matrix_folder = null;
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Type", inversedBy="catalogs")
     */
    private ?Type $type = null;
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Material", inversedBy="catalogs")
     */
    private ?Material $material = null;
    
    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private ?float $price = null;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $recommendedTitle = null;
    
    /**
     * @ORM\OneToMany(targetEntity=WorkExample::class, mappedBy="catalog")
     */
    private Collection $workExamples;
    
    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private ?array $filters = [];
    
    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private bool $hideCategories = false;
    
    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private bool $hideFilters = false;
    
    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private ?string $seoType = null;
    
    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private ?array $catalogLinks = [];
    
    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private ?array $excludedMaterials = [];
    
    /**
     * @ORM\Column(type="boolean", options={"default": false})
     * True - если каталог не имеет собственных товаров, а лишь агрегирует несколько каталогов
     */
    private bool $aggregateCatalog = false;
    
    /**
     * @ORM\OneToMany(targetEntity=Location::class, mappedBy="baseCatalog")
     * @ORM\OrderBy({"ordering" = "ASC", "id" = "ASC",})
     */
    private Collection $locations;
    
    public function __construct()
    {
        parent::__construct();
        $this->workExamples = new ArrayCollection();
        $this->locations    = new ArrayCollection();
    }
    
    public function getPrice(): ?float
    {
        return $this->price;
    }
    
    public function setPrice(?float $price): self
    {
        $this->price = $price;
        
        return $this;
    }
    
    public function getType(): ?Type
    {
        if ($this->type) {
            return $this->type;
        }
        $parent = $this->getParent();
        if ($parent && $parent instanceof Catalog) {
            return $parent->getType();
        }
        
        return null;
    }
    
    public function setType(?Type $type): self
    {
        $this->type = $type;
        
        return $this;
    }
    
    public function getMaterial(): ?Material
    {
        if ($this->material) {
            return $this->material;
        }
        
        $parent = $this->getParent();
        if ($parent && $parent instanceof Catalog) {
            return $parent->getMaterial();
        }
        
        return null;
    }
    
    public function setMaterial(?Material $material): self
    {
        $this->material = $material;
        
        return $this;
    }
    
    public function getRecommendedTitle(): ?string
    {
        return $this->recommendedTitle ?? 'Рекомендуемые ' . $this->name;
    }
    
    public function setRecommendedTitle(?string $recommendedTitle): self
    {
        $this->recommendedTitle = $recommendedTitle;
        
        return $this;
    }
    
    public function getDescriptionComputed()
    {
        if (!empty($this->getDescription())) {
            return $this->getDescription();
        }
    
        return sprintf('%s купить недорого с установкой в $city_prepositional. ⭐ Каталог и цены. ✅ Выезд и замер бесплатно. ✅ Гарантия 2 года.',
            $this->getName());
    }
    
    public function getUnits(): string
    {
        if (in_array(explode('/', $this->getUri())[0], ['markizyi', 'rulonnyie-shtoryi'])) {
            return 'руб за изделие';
        }
        
        return parent::getUnits();
    }
    
    public function getTurboContentTemplate(): string
    {
        return 'turbo/catalog/content.html.twig';
    }
    
    /**
     * @return Collection<WorkExample>
     */
    public function getWorkExamples(): Collection
    {
        return $this->workExamples;
    }
    
    public function addWorkExample(WorkExample $workExample): self
    {
        if (!$this->workExamples->contains($workExample)) {
            $this->workExamples[] = $workExample;
            $workExample->setCatalog($this);
        }
        
        return $this;
    }
    
    public function removeWorkExample(WorkExample $workExample): self
    {
        if ($this->workExamples->removeElement($workExample)) {
            // set the owning side to null (unless already changed)
            if ($workExample->getCatalog() === $this) {
                $workExample->setCatalog(null);
            }
        }
        
        return $this;
    }
    
    public function isHideCategories(): bool
    {
        if ($this->hideCategories) {
            return true;
        }
        
        return $this->getType()?->isHideCategories() ?? false;
    }
    
    public function getMatrixFolder(): ?string
    {
        $parent = $this->getParent();
        if (
            null === $this->matrix_folder
            && null !== $parent
            && $parent instanceof Catalog
        ) {
            return $parent->getMatrixFolder();
        }
        
        return $this->matrix_folder;
    }
    
    public function setMatrixFolder(?string $matrix_folder): self
    {
        $this->matrix_folder = $matrix_folder;
        
        return $this;
    }
    
    /**
     * @return array
     */
    public function getFilters(): array
    {
        return $this->filters ?? [];
    }
    
    /**
     * @param array|null $filters
     *
     * @return $this
     */
    public function setFilters(?array $filters): self
    {
        $this->filters = $filters;
        
        return $this;
    }
    
    /**
     * @param bool $hideCategories
     *
     * @return $this
     */
    public function setHideCategories(bool $hideCategories): self
    {
        $this->hideCategories = $hideCategories;
        
        return $this;
    }
    
    /**
     * @return bool
     */
    public function isHideFilters(): bool
    {
        return $this->hideFilters;
    }
    
    /**
     * @param bool $hideFilters
     *
     * @return $this
     */
    public function setHideFilters(bool $hideFilters): self
    {
        $this->hideFilters = $hideFilters;
        
        return $this;
    }
    
    /**
     * @return bool
     */
    public function isPremium(): bool
    {
        return $this->seoType === self::SEO_TYPE_PREMIUM;
    }
    
    public function isShowSummary(): bool
    {
        return null !== $this->nameGenitive;
    }
    
    public function getAvailableTypes(): ?array
    {
        if ($this->uri === 'zhalyuzi') {
            return [132, 133, 175, 178, 86]; //Все, кроме вертикальных
        }
        $types = $this->getFilters()['type'] ?? null;
        if (null === $types) {
            return null;
        }
        $typesArray = explode(',', $types);
        
        return array_map(static fn(string $item) => (int)$item, $typesArray);
    }
    
    public function getSelectedCategory(): int
    {
        $categories = $this->getFilters()['category'] ?? null;
        if (null === $categories) {
            return 1;
        }
        $categoriesArray = explode(',', $categories);
        
        return (int)$categoriesArray[0];
    }
    
    /**
     * @return bool
     */
    public function isNoDrill(): bool
    {
        return $this->seoType === self::SEO_TYPE_NO_DRILL;
    }
    
    /**
     * @return bool
     */
    public function isWithInstallation(): bool
    {
        return $this->seoType === self::SEO_TYPE_WITH_INSTALLATION;
    }
    
    /**
     * @return bool
     */
    public function isForOrder(): bool
    {
        return $this->seoType === self::SEO_TYPE_FOR_ORDER;
    }
    
    /**
     * @return string|null
     */
    public function getSeoType(): ?string
    {
        return $this->seoType;
    }
    
    /**
     * @param string|null $seoType
     *
     * @return $this
     */
    public function setSeoType(?string $seoType): self
    {
        $this->seoType = $seoType;
        
        return $this;
    }
    
    /**
     * @return array
     */
    public function getCatalogLinks(): array
    {
        return $this->catalogLinks ?? [];
    }
    
    /**
     * @param array|null $catalogLinks
     *
     * @return $this
     */
    public function setCatalogLinks(?array $catalogLinks): self
    {
        $this->catalogLinks = $catalogLinks;
        
        return $this;
    }
    
    /**
     * @return array
     */
    public function getExcludedMaterials(): array
    {
        return $this->excludedMaterials ?? [];
    }
    
    /**
     * @param array|null $excludedMaterials
     *
     * @return $this
     */
    public function setExcludedMaterials(?array $excludedMaterials): self
    {
        $this->excludedMaterials = $excludedMaterials;
        
        return $this;
    }
    
    /**

src/Entity/Geo.php
<?php

namespace App\Entity;

use App\Entity\Contracts\HasCatalogSettingsInterface;
use App\Entity\Traits\CatalogSettingsTrait;
use App\Model\GeoProduct\AbstractGeoProduct;
use App\Model\GeoProduct\RulonnyieShtoryiGeoProduct;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\EntityListeners({"App\EntityListener\GeoListener"})
 */
abstract class Geo extends Page implements HasCatalogSettingsInterface
{
    
    use CatalogSettingsTrait;
    
    public const TYPE = 'geo';
    /**
     * @var AbstractGeoProduct
     */
    protected $geoProduct;
    
    /**
     * @return AbstractGeoProduct
     */
    public function getGeoProduct(): AbstractGeoProduct
    {
        if (null === $this->geoProduct) {
            $this->geoProduct = AbstractGeoProduct::create($this->getGeoProductType());
        }
        
        return $this->geoProduct;
    }
    
    public function getCardHeader(): string
    {
        return $this->getH1() . ' цена';
    }
    
    public function getCardDescription(): string
    {
        return sprintf('<p><span><b>Материал:</b> ткань, алюминий, пластик, дерево.</span> <span><b>Цвет:</b> на выбор.</span> <span><b>Размеры:</b> стандартные и под заказ</span> <span><b>Тип:</b> горизонтальные и вертикальные.</span> <span><b>Виды:</b> алюминиевые, пластиковые, деревянные, тканевые.</span> <span><b>Помещения:</b>&nbsp;терраса&nbsp;</span><span><b>Управление:</b> механическое и автоматическое</span> <span><b>Срок изготовления и установки:</b> 2-7 дней (зависит от сложности и объема).</span> <span><b>Замер:</b> бесплатный (при оформлении и оплате заказа).</span> <span><b>Доставка и установка %s:</b> в $city_and_region_prepositional.</span> <span>Возможна доставка и установка по России</span></p>',
            $this->getGeoProduct()->getNameGenitive());
    }
    
    public function getCardImageUrl(): string
    {
        return $this->getGeoProduct()->getCardImage();
    }
    
    public function getTypeFilter(): string
    {
        return $this->getGeoProductType() === RulonnyieShtoryiGeoProduct::TYPE ? '133' : '86,132,178';
    }
    
    public function isShowCatalog(): bool
    {
        return $this instanceof City
               || in_array($this->getUri(), ['moskovskoy-oblasti', 'rulonnyie-shtoryi/moskovskoy-oblasti']);
    }
    
    public function getBaseCatalogUri(): string
    {
        return $this->getGeoProductType() === RulonnyieShtoryiGeoProduct::TYPE ? 'rulonnyie-shtoryi' : 'vertikalnye-zhalyuzi-na-okna';
    }
}

src/Controller/YmlController.php
<?php

namespace App\Controller;

use App\Entity\Catalog;
use App\Repository\CategoryRepository;
use App\Repository\PageRepository;
use App\Repository\ProductRepository;
use App\Service\CatalogManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class YmlController extends AbstractController
{
    
    /**
     * @Route("/{token}.yml", name="dynamic_yaml",requirements={"token"=".+"}, format="xml")
     * @param string         $token
     * @param PageRepository $pageRepository
     * @param CatalogManager $catalogManager
     *
     * @return Response
     */
    public function dynamicYaml(
        string $token,
        PageRepository $pageRepository,
        CatalogManager $catalogManager
    ): Response {
        if (!$catalog = $pageRepository->findOneBy(['uri' => $token])) {
            throw new NotFoundHttpException();
        }
        if (!$catalog instanceof Catalog) {
            throw new NotFoundHttpException();
        }
        $offers = $catalogManager->getPopular($catalog);
        
        return $this->render('yml/index.xml.twig', [
            'offers' => $offers,
            'page'   => $catalog,
        ]);
    }
    
    /**
     * @Route("/ymarket.xml", name="ymarket", format="xml")
     *
     * @param ProductRepository  $productRepository
     * @param CategoryRepository $categoryRepository
     *
     * @return Response
     */
    public function ymarket(ProductRepository $productRepository, CategoryRepository $categoryRepository)
    {
        return $this->render('yml/ymarket.xml.twig', [
            'offers'     => $productRepository->getForYml(),
            'categories' => $categoryRepository->findAll(),
        ]);
    }
    
    /**
     * @Route("/ymarket-cards.xml", name="ymarket_cards", format="xml")
     *
     * @param ProductRepository $productRepository
     *
     * @return Response
     */
    public function ymarketCards(ProductRepository $productRepository)
    {
        return $this->render('yml/ymarket-cards.xml.twig', [
            'offers' => $productRepository->getForYml(),
        ]);
    }
}

templates/yml/index.xml.twig
<?xml version="1.0" encoding="UTF-8"?>
<yml_catalog date="{{ 'now'|date('Y-m-d H:i') }}">
    <shop>
        <name>{{ page.name }}</name>
        <company>{{ page.descriptionComputed }}</company>
        <url>{{ app.request.schemeAndHttpHost }}{{ page.path }}</url>
        <currencies>
            <currency id="RUR" rate="1" />
        </currencies>
        <categories>
            <category id="1">Товары в наличии</category>
        </categories>
        <offers>
            {% for offer in offers -%}
            <offer id="{{ offer.id }}" available="true">
                <url>{{ app.request.schemeAndHttpHost~offer.path }}</url>
                <price>{{ min_price(offer,true) }}</price>
                <currencyId>RUR</currencyId>
                <categoryId>1</categoryId>
                <name>{{ offer.name }}</name>
                <description>{{ offer.descriptionComputed }}</description>
                <manufacturer_warranty>true</manufacturer_warranty>
                <delivery>false</delivery>
                <picture>{{ app.request.schemeAndHttpHost }}{{ offer.cardImageUrl }}</picture>
            </offer>
            {% endfor -%}
        </offers>
    </shop>
</yml_catalog>

templates/yml/ymarket-cards.xml.twig
{% set categories = constant('App\\Entity\\Product::YML_CATEGORIES') -%}
<?xml version="1.0" encoding="UTF-8"?>
<yml_catalog date="{{ 'now'|date('Y-m-d H:i') }}">
    <shop>
        <name>Мастерская Жалюзи</name>
        <company>Жалюзи на окна купить недорого в Москве. Выезд и замер бесплатно!</company>
        <url>{{ app.request.schemeAndHttpHost }}</url>
        <currencies>
            <currency id="RUR" rate="1" />
        </currencies>
        <categories>
            {% for category in categories %}
                <category id="{{ category.id }}">{{ category.name }}</category>
            {% endfor %}
        
        </categories>
        <delivery-options>
            <option cost="500" days="3" />
        </delivery-options>
        <offers>
            {% for offer in offers -%}
                <offer id="{{ offer.id }}" available="true">
                    <url>{{ app.request.schemeAndHttpHost~offer.path }}</url>
                    <price>{{ min_price(offer, true, true) }}</price>
                    <currencyId>RUR</currencyId>
                    <categoryId>{{ offer.ymlCategory.id }}</categoryId>
                    <name>{{ offer.name }} ({{ offer.minSize }}, {{ offer.colorName }})</name>
                    <description>
                        <![CDATA[
                        <h3>{{ offer.cardHeader }} характеристики:</h3>
                        <br/>
                        <ul>
                            <li>Вид: {{ offer.typeNameForPage }}</li>
                            {% if offer.typeForPage -%}
                            <li>Тип: {{ offer.typeForPage }}</li>
                            {%- endif %}
                            
                            <li>Цвет: {{ offer.colorName }}</li>
                            <li>Категория: {{ offer.ymlCategory.name }}</li>
                            <li>Размер: На ваш выбор.</li>
                            <li>Управление: Ручное и автоматическое</li>
                            <li>Срок изготовления и установки: 1-5 дней</li>
                        </ul>
                    ]]>
                    </description>
                    <manufacturer_warranty>true</manufacturer_warranty>
                    <picture>{{ app.request.schemeAndHttpHost }}{{ offer.cardImageUrl }}</picture>
                    <param name="Вид">{{ offer.typeNameForPage }}</param>
                    {% if offer.typeForPage -%}
                        <param name="Тип">{{ offer.typeForPage }}</param>
                    {%- endif %}
                    
                    <param name="Материал">{{ offer.materialForPage }}</param>
                    <param name="Цвет">{{ offer.colorName }}</param>
                    <param name="Категория">{{ offer.ymlCategory.name }}</param>
                    <param name="Размер">{{ offer.minSize }}</param>
                    <param name="Управление">ручное и автоматическое</param>
                    <param name="Срок изготовления и установки">1-5 дней</param>
                    <param name="Выезд и замер">бесплатный при оформлении заказа и оплате</param>
                </offer>
            {% endfor -%}
        </offers>
    </shop>
</yml_catalog>

templates/yml/ymarket.xml.twig
<?xml version="1.0" encoding="UTF-8"?>
<yml_catalog date="{{ 'now'|date('Y-m-d H:i') }}">
    <shop>
        <name>Мастерская Жалюзи</name>
        <company>Жалюзи на окна купить недорого в $city_prepositional. Выезд и замер бесплатно!</company>
        <url>{{ app.request.schemeAndHttpHost }}</url>
        <currencies>
            <currency id="RUR" rate="1" />
        </currencies>
        <categories>
            {% for category in categories %}
                <category id="{{ category.id }}">{{ category.name }}</category>
            {% endfor %}
        </categories>
        <delivery-options>
            <option cost="500" days="3"/>
        </delivery-options>
        <offers>
            {% for offer in offers -%}
            <offer id="{{ offer.id }}" available="true">
                <url>{{ app.request.schemeAndHttpHost~offer.path }}</url>
                <price>{{ min_price(offer,true) }}</price>
                <currencyId>RUR</currencyId>
                <categoryId>{{ offer.category.id ?? 1 }}</categoryId>
                <name>{{ offer.name }} ({{ offer.minSize }}, {{ offer.colorName }})</name>
                <description>{{ offer.descriptionComputed }}</description>
                <manufacturer_warranty>true</manufacturer_warranty>
                <picture>{{ app.request.schemeAndHttpHost }}{{ offer.cardImageUrl }}</picture>
                <param name="Вид">{{ offer.typeNameForPage }}</param>
                <param name="Тип">{{ offer.typeForPage }}</param>
                <param name="Материал">{{ offer.materialForPage }}</param>
                <param name="Цвет">{{ offer.colorName }}</param>
                <param name="Категория">{{ offer.categoryName }}</param>
                <param name="Размер">{{ offer.minSize }}</param>
                <param name="Управление">ручное и автоматическое</param>
                <param name="Срок изготовления и установки">1-5 дней</param>
                <param name="Выезд и замер">бесплатный при оформлении заказа и оплате</param>
            </offer>
            {% endfor -%}
        </offers>
    </shop>
</yml_catalog>